# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.9.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.9.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/cesar/workspace/tools/xdiff-c

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/cesar/workspace/tools/xdiff-c

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.9.0/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.9.0/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/cesar/workspace/tools/xdiff-c/CMakeFiles /Users/cesar/workspace/tools/xdiff-c/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/cesar/workspace/tools/xdiff-c/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named xdiff

# Build rule for target.
xdiff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xdiff
.PHONY : xdiff

# fast build rule for target.
xdiff/fast:
	$(MAKE) -f CMakeFiles/xdiff.dir/build.make CMakeFiles/xdiff.dir/build
.PHONY : xdiff/fast

XDiff.o: XDiff.cpp.o

.PHONY : XDiff.o

# target to build an object file
XDiff.cpp.o:
	$(MAKE) -f CMakeFiles/xdiff.dir/build.make CMakeFiles/xdiff.dir/XDiff.cpp.o
.PHONY : XDiff.cpp.o

XDiff.i: XDiff.cpp.i

.PHONY : XDiff.i

# target to preprocess a source file
XDiff.cpp.i:
	$(MAKE) -f CMakeFiles/xdiff.dir/build.make CMakeFiles/xdiff.dir/XDiff.cpp.i
.PHONY : XDiff.cpp.i

XDiff.s: XDiff.cpp.s

.PHONY : XDiff.s

# target to generate assembly for a file
XDiff.cpp.s:
	$(MAKE) -f CMakeFiles/xdiff.dir/build.make CMakeFiles/xdiff.dir/XDiff.cpp.s
.PHONY : XDiff.cpp.s

XHash.o: XHash.cpp.o

.PHONY : XHash.o

# target to build an object file
XHash.cpp.o:
	$(MAKE) -f CMakeFiles/xdiff.dir/build.make CMakeFiles/xdiff.dir/XHash.cpp.o
.PHONY : XHash.cpp.o

XHash.i: XHash.cpp.i

.PHONY : XHash.i

# target to preprocess a source file
XHash.cpp.i:
	$(MAKE) -f CMakeFiles/xdiff.dir/build.make CMakeFiles/xdiff.dir/XHash.cpp.i
.PHONY : XHash.cpp.i

XHash.s: XHash.cpp.s

.PHONY : XHash.s

# target to generate assembly for a file
XHash.cpp.s:
	$(MAKE) -f CMakeFiles/xdiff.dir/build.make CMakeFiles/xdiff.dir/XHash.cpp.s
.PHONY : XHash.cpp.s

XLut.o: XLut.cpp.o

.PHONY : XLut.o

# target to build an object file
XLut.cpp.o:
	$(MAKE) -f CMakeFiles/xdiff.dir/build.make CMakeFiles/xdiff.dir/XLut.cpp.o
.PHONY : XLut.cpp.o

XLut.i: XLut.cpp.i

.PHONY : XLut.i

# target to preprocess a source file
XLut.cpp.i:
	$(MAKE) -f CMakeFiles/xdiff.dir/build.make CMakeFiles/xdiff.dir/XLut.cpp.i
.PHONY : XLut.cpp.i

XLut.s: XLut.cpp.s

.PHONY : XLut.s

# target to generate assembly for a file
XLut.cpp.s:
	$(MAKE) -f CMakeFiles/xdiff.dir/build.make CMakeFiles/xdiff.dir/XLut.cpp.s
.PHONY : XLut.cpp.s

XParser.o: XParser.cpp.o

.PHONY : XParser.o

# target to build an object file
XParser.cpp.o:
	$(MAKE) -f CMakeFiles/xdiff.dir/build.make CMakeFiles/xdiff.dir/XParser.cpp.o
.PHONY : XParser.cpp.o

XParser.i: XParser.cpp.i

.PHONY : XParser.i

# target to preprocess a source file
XParser.cpp.i:
	$(MAKE) -f CMakeFiles/xdiff.dir/build.make CMakeFiles/xdiff.dir/XParser.cpp.i
.PHONY : XParser.cpp.i

XParser.s: XParser.cpp.s

.PHONY : XParser.s

# target to generate assembly for a file
XParser.cpp.s:
	$(MAKE) -f CMakeFiles/xdiff.dir/build.make CMakeFiles/xdiff.dir/XParser.cpp.s
.PHONY : XParser.cpp.s

XTree.o: XTree.cpp.o

.PHONY : XTree.o

# target to build an object file
XTree.cpp.o:
	$(MAKE) -f CMakeFiles/xdiff.dir/build.make CMakeFiles/xdiff.dir/XTree.cpp.o
.PHONY : XTree.cpp.o

XTree.i: XTree.cpp.i

.PHONY : XTree.i

# target to preprocess a source file
XTree.cpp.i:
	$(MAKE) -f CMakeFiles/xdiff.dir/build.make CMakeFiles/xdiff.dir/XTree.cpp.i
.PHONY : XTree.cpp.i

XTree.s: XTree.cpp.s

.PHONY : XTree.s

# target to generate assembly for a file
XTree.cpp.s:
	$(MAKE) -f CMakeFiles/xdiff.dir/build.make CMakeFiles/xdiff.dir/XTree.cpp.s
.PHONY : XTree.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... xdiff"
	@echo "... XDiff.o"
	@echo "... XDiff.i"
	@echo "... XDiff.s"
	@echo "... XHash.o"
	@echo "... XHash.i"
	@echo "... XHash.s"
	@echo "... XLut.o"
	@echo "... XLut.i"
	@echo "... XLut.s"
	@echo "... XParser.o"
	@echo "... XParser.i"
	@echo "... XParser.s"
	@echo "... XTree.o"
	@echo "... XTree.i"
	@echo "... XTree.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

